#define SCULL_IOC_MAGIC 0x98

#define SCULL_IOCRESET _IO(SCULL_IOC_MAGIC, 0)

#define SCULL_IOCSQUANTUM _IOW(SCULL_IOC_MAGIC, 1, int)


#define SCULL_IOCGQUANTUM _IOR(SCULL_IOC_MAGIC, 5, int)

#define _IOC_TYPE_GARY(nr)		(((nr) >> _IOC_TYPESHIFT) & _IOC_TYPEMASK)

#define SCULL_IOC_MAXNR 14
